/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description ¿Esta vivo el proceso?
         *
         *     No toca la base de datos ni pide autenticacion, a proposito: si dependiera
         *     de algo mas, una base de datos caida provocaria reinicios en bucle que no
         *     arreglarian la base de datos.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description ¿Puede la aplicacion atender trabajo real?
         *
         *     Devuelve 503 si alguna comprobacion falla, para que el resultado sea util a
         *     un supervisor sin tener que leer el cuerpo de la respuesta.
         */
        get: operations["ready_api_v1_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Obtener un par de tokens
         * @description Comprueba usuario y contraseña y devuelve access + refresh.
         *
         *     Responde lo mismo —401 y "usuario o contraseña incorrectos"— tanto si el
         *     usuario no existe como si la contraseña falla o la cuenta esta desactivada.
         *     El motivo real queda en `audit_events`, que es donde sirve para algo.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar el access token
         * @description Cambia un refresh token valido por un par nuevo.
         *
         *     No consume el token entregado: en el MVP el refresco es stateless y no hay
         *     donde marcarlo como usado (ADR-0008). Lo que si se comprueba es que la
         *     cuenta siga existiendo y activa.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quien soy
         * @description El usuario del token actual.
         *
         *     Es lo que el frontend llama al arrancar para saber si la sesion guardada
         *     sigue viva y que puede enseñar segun el rol.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar reglas
         * @description Las reglas, ordenadas como se aplican: por cadena y posicion.
         *
         *     Leer no exige mas que estar autenticado. Un `viewer` es precisamente el rol
         *     de quien tiene que poder auditar la politica sin poder cambiarla.
         */
        get: operations["listar_api_v1_rules_get"];
        put?: never;
        /**
         * Crear una regla
         * @description Crea una regla al final de su cadena y, con `AUTO_APPLY`, la aplica.
         *
         *     La respuesta devuelve los valores NORMALIZADOS, que pueden no ser los que se
         *     mandaron: `1.2.3.4` vuelve como `1.2.3.4/32`. Es deliberado —el frontend
         *     tiene que enseñar lo que se guardo, no lo que se escribio— y es lo que hace
         *     que la deteccion de drift pueda comparar por estructura (ADR-0006).
         *
         *     El `sync_state` de la respuesta dice como acabo: `applied` si se aplico,
         *     `pending` con `AUTO_APPLY=false`, `failed` si el firewall no pudo. Es 201 en
         *     los tres casos, porque en los tres la regla existe.
         */
        post: operations["crear_api_v1_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reordenar una cadena
         * @description Reescribe el orden de una cadena entera.
         *
         *     Va declarado ANTES que `/{uuid}` no por casualidad: FastAPI resuelve las
         *     rutas en orden de registro, y con `/{uuid}` delante, `/rules/reorder`
         *     entraria por ahi con el uuid literal `"reorder"`.
         *
         *     El cuerpo tiene que traer todas las reglas de la cadena. Si falta alguna,
         *     409 con la lista de las que faltan: es un error del cliente y se puede
         *     arreglar sin adivinar.
         */
        post: operations["reordenar_api_v1_rules_reorder_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver una regla
         * @description Una regla completa, con su estado de sincronizacion y su ultimo error.
         */
        get: operations["ver_api_v1_rules__uuid__get"];
        put?: never;
        post?: never;
        /**
         * Borrar una regla
         * @description Borra la regla de la base de datos y reconstruye su cadena.
         *
         *     Con `AUTO_APPLY=false` la regla sigue viva en iptables hasta la siguiente
         *     reconciliacion, y eso no es un fallo: la fuente de verdad es la DB y el
         *     firewall la refleja, no al reves (ADR-0001). El `sync_state` de la cadena es
         *     lo que hace visible esa distancia.
         *
         *     Por eso `delete_rule` devuelve la cadena: la fila ya no existe y sin ese dato
         *     habria que adivinarla o reconstruir las tres para nada.
         */
        delete: operations["borrar_api_v1_rules__uuid__delete"];
        options?: never;
        head?: never;
        /**
         * Modificar una regla
         * @description Modificacion parcial: solo se toca lo que venga en el cuerpo.
         *
         *     `PATCH` y no `PUT` porque el cliente no tiene por que conocer la regla
         *     entera para cambiarle el puerto, y porque mandarla entera abriria la puerta
         *     a pisar sin querer un campo que otro acaba de cambiar.
         */
        patch: operations["modificar_api_v1_rules__uuid__patch"];
        trace?: never;
    };
    "/api/v1/rules/{uuid}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activar o desactivar una regla
         * @description Invierte `enabled`. La regla sigue existiendo; el renderer la omite.
         *
         *     Desactivar en vez de borrar es lo que permite probar si una regla es la que
         *     esta rompiendo algo y devolverla en un clic, con su descripcion intacta.
         */
        post: operations["alternar_api_v1_rules__uuid__toggle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firewall/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconciliar la politica contra el firewall
         * @description Reconstruye las tres cadenas gestionadas desde la base de datos.
         *
         *     Una sola operacion, tanto si has añadido una regla como si has borrado diez:
         *     se vacia la cadena y se reconstruye entera, en orden (ADR-0002). De ahi que
         *     sea idempotente y que no existan `add_rule` ni `delete_rule`.
         *
         *     Aqui SI se propaga el fallo del firewall como 502: quien llama a este
         *     endpoint esta pidiendo explicitamente que se aplique, y decirle que ha ido
         *     bien cuando no ha ido bien seria mentirle. Es la diferencia con el
         *     auto-apply, donde el 502 escondería que la regla si se creo.
         */
        post: operations["aplicar_api_v1_firewall_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firewall/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ver los comandos sin ejecutarlos
         * @description Los comandos exactos que ejecutaria `apply`, sin ejecutar ninguno.
         *
         *     Pide rol `operator` aunque solo lea. No es por el contenido de las reglas
         *     —un `viewer` ya puede listarlas— sino porque la salida incluye las reglas
         *     guardian, y con ellas el puerto y el rango desde los que se administra la
         *     maquina. Eso es topologia de la red de gestion, y quien no puede aplicar
         *     tampoco necesita conocerla. Relajarlo a `viewer` es cambiar una palabra.
         */
        get: operations["previsualizar_api_v1_firewall_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/firewall/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado del firewall: drift, contadores y pendientes
         * @description Compara `iptables -S FWDASH_*` con la base de datos y devuelve la foto.
         *
         *     Es lo que alimenta el badge de estado y el banner de drift. Un dashboard que
         *     solo enseñe la tabla `rules` esta enseñando una intencion; este endpoint es
         *     el que la convierte en un estado.
         *
         *     De paso refresca los contadores de paquetes y bytes de cada regla: es la
         *     misma lectura del sistema, y separarla en otro endpoint solo daria una cosa
         *     mas que el frontend tendria que acordarse de llamar.
         */
        get: operations["estado_api_v1_firewall_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @description Targets permitidos para una regla de usuario.
         *
         *     `LOG` no aparece aqui a proposito: no es una accion que el usuario elija, sino
         *     una regla adicional que el renderer emite cuando `log_enabled` esta activo
         *     (fase 2).
         * @enum {string}
         */
        Action: "ACCEPT" | "DROP" | "REJECT";
        /**
         * ApplyResponse
         * @description Respuesta de `POST /firewall/apply` y de `GET /firewall/preview`.
         *
         *     Es la misma forma para los dos a proposito: el preview no es un modo
         *     escondido ni un endpoint aparte que pueda divergir, es la misma
         *     reconciliacion con `dry_run=True`. Si el preview y el apply pudieran dar
         *     listas distintas, el preview no serviria para lo unico que existe.
         */
        ApplyResponse: {
            /** Dry Run */
            dry_run: boolean;
            /** Chains */
            chains: components["schemas"]["ChainApply"][];
            /**
             * Applied At
             * @description Nulo en un preview: no se ha ejecutado nada.
             */
            applied_at?: string | null;
        };
        /**
         * Chain
         * @description Cadenas del sistema gestionadas por la aplicacion.
         * @enum {string}
         */
        Chain: "INPUT" | "OUTPUT" | "FORWARD";
        /**
         * ChainApply
         * @description Lo que se ha hecho —o se haria— con una cadena.
         */
        ChainApply: {
            chain: components["schemas"]["Chain"];
            /**
             * Applied
             * @description Reglas de usuario que quedan en la cadena.
             */
            applied: number;
            /** Commands */
            commands: string[];
        };
        /**
         * ChainDrift
         * @description Diferencia entre lo que dice la base de datos y lo que hay en la cadena.
         *
         *     `missing` y `pending` son las dos mitades de "esta en la DB y no en
         *     iptables", y separarlas importa: una regla recien creada todavia no se ha
         *     aplicado y eso es normal; una regla que se creia aplicada y no esta significa
         *     que alguien toco el firewall por fuera. Solo lo segundo es drift.
         */
        ChainDrift: {
            chain: components["schemas"]["Chain"];
            /** Has Drift */
            has_drift: boolean;
            /**
             * Managed
             * @description Reglas gestionadas leidas de la cadena.
             */
            managed: number;
            /**
             * Missing
             * @description Uuids de reglas que se creian aplicadas y no estan en la cadena.
             */
            missing?: string[];
            /**
             * Pending
             * @description Uuids de reglas aun sin aplicar. No son drift.
             */
            pending?: string[];
            /**
             * Unexpected
             * @description Lineas presentes en la cadena que no salen de la base de datos.
             */
            unexpected?: string[];
            /**
             * Out Of Order
             * @description Estan todas las reglas, pero en otro orden. En iptables el orden es la semantica.
             * @default false
             */
            out_of_order: boolean;
        };
        /**
         * ErrorBody
         * @description Contenido de un error. `details` es libre, pero siempre saneado.
         */
        ErrorBody: {
            /**
             * Code
             * @description Identificador estable del error, apto para 'switch' en el front.
             */
            code: string;
            /**
             * Message
             * @description Mensaje legible, en español, orientado a la persona.
             */
            message: string;
            /**
             * Details
             * @description Contexto adicional. Nunca contiene stderr crudo ni rutas del sistema.
             */
            details?: {
                [key: string]: unknown;
            };
            /**
             * Request Id
             * @description Identificador de la peticion. Es lo que se busca en los logs.
             */
            request_id?: string | null;
        };
        /**
         * ErrorResponse
         * @description Envoltorio unico de TODOS los errores de la API.
         *
         *     Que el frontend solo tenga que entender una forma de error es lo que permite
         *     tener un unico interceptor en `api/client.ts` en vez de un `if` por endpoint.
         * @example {
         *       "error": {
         *         "code": "invalid_rule",
         *         "details": {
         *           "field": "dst_port"
         *         },
         *         "message": "El puerto '99999' esta fuera del rango valido (1-65535).",
         *         "request_id": "01J8ZQ4T2N6R7V9WXYZ0ABCDEF"
         *       }
         *     }
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * FirewallStatus
         * @description Respuesta de `GET /firewall/status`: la foto que pinta el dashboard.
         */
        FirewallStatus: {
            /**
             * Backend
             * @description 'fake' o 'iptables'.
             */
            backend: string;
            /**
             * Scaffold Ok
             * @description Existen las cadenas gestionadas FWDASH_*.
             */
            scaffold_ok: boolean;
            /** Has Drift */
            has_drift: boolean;
            /** Chains */
            chains: components["schemas"]["ChainDrift"][];
            /** Rules Total */
            rules_total: number;
            /** Rules Pending */
            rules_pending: number;
            /** Last Applied At */
            last_applied_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Respuesta de `/health`. Deliberadamente minima: es un liveness probe.
         */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /**
         * LoginRequest
         * @description Credenciales de entrada.
         *
         *     Los limites son de cordura, no de politica de contraseñas: rechazar aqui una
         *     contraseña de 5 caracteres solo le diria al atacante que no lo intente. La
         *     politica, cuando la haya, va en la creacion del usuario.
         * @example {
         *       "password": "***",
         *       "username": "admin"
         *     }
         */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Page[RuleListItem] */
        Page_RuleListItem_: {
            /** Items */
            items: components["schemas"]["RuleListItem"][];
            /**
             * Total
             * @description Total de elementos que cumplen el filtro.
             */
            total: number;
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Size
             * @default 50
             */
            size: number;
        };
        /**
         * Protocol
         * @enum {string}
         */
        Protocol: "tcp" | "udp" | "icmp" | "all";
        /**
         * ReadinessResponse
         * @description Respuesta de `/ready`: si la aplicacion puede atender trabajo real.
         *
         *     La diferencia con `/health` no es burocracia. `/health` dice "el proceso
         *     esta vivo"; `/ready` dice "sus dependencias responden". Un proceso vivo con
         *     la base de datos caida debe seguir contestando al primero y fallar el
         *     segundo, o el supervisor lo reiniciaria en bucle sin arreglar nada.
         */
        ReadinessResponse: {
            /**
             * Status
             * @description 'ready' o 'degraded'.
             */
            status: string;
            /**
             * Checks
             * @description Resultado por dependencia.
             */
            checks: {
                [key: string]: string;
            };
            /**
             * Firewall Backend
             * @description Backend configurado: 'fake' o 'iptables'.
             */
            firewall_backend: string;
        };
        /**
         * RefreshRequest
         * @description El refresh viaja en el cuerpo, no en la cabecera `Authorization`.
         *
         *     Asi el interceptor del frontend puede tener una regla unica —"pon el access
         *     token en `Authorization`"— sin excepciones para un endpoint.
         */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * ReorderRequest
         * @description Nuevo orden de una cadena, de la primera regla a la ultima.
         *
         *     La lista tiene que contener TODAS las reglas de la cadena, no un
         *     subconjunto: un reorden parcial dejaria a las que faltan con posiciones
         *     antiguas que pueden chocar con las nuevas, y `UniqueConstraint(chain,
         *     position)` lo rechazaria a mitad de la operacion.
         *
         *     La cadena no se manda en el cuerpo: se deduce de las reglas, y que todas
         *     sean de la misma cadena es parte de la validacion. Pedirla ademas solo
         *     añadiria una forma nueva de equivocarse —mandar una cadena que no es la de
         *     las reglas— sin aportar nada.
         */
        ReorderRequest: {
            /**
             * Uuids
             * @description Uuids en el orden deseado.
             */
            uuids: string[];
        };
        /**
         * Role
         * @description Roles del RBAC, de mayor a menor privilegio.
         *
         *     Vive aqui y no en `firewall/spec.py` porque no es un concepto de red: la
         *     capa de firewall no sabe que existen los usuarios.
         * @enum {string}
         */
        Role: "admin" | "operator" | "viewer";
        /**
         * RuleCreate
         * @description Alta de una regla.
         *
         *     No lleva `position`: las reglas se añaden al final de su cadena y el orden se
         *     cambia con `POST /rules/reorder`. Dejar elegir la posicion en el alta
         *     obligaria a resolver colisiones con `UniqueConstraint(chain, position)` en
         *     cada insercion, y la UI arrastra filas, no escribe numeros.
         *
         *     Tampoco lleva `table_name` ni `ip_version`: el MVP solo genera IPv4 en la
         *     tabla `filter`. Ambas columnas existen en el modelo para que añadir `nat` o
         *     ip6tables no exija migrar el esquema, pero aceptarlas hoy dejaria crear
         *     reglas que el renderer rechaza al aplicarlas: un error a destiempo y en el
         *     sitio equivocado.
         * @example {
         *       "action": "DROP",
         *       "chain": "INPUT",
         *       "description": "Rafagas de SSH desde este /24 desde el 28 de agosto.",
         *       "dst_port": "22",
         *       "name": "Bloquear escaner del puerto 22",
         *       "protocol": "tcp",
         *       "src_ip": "203.0.113.0/24"
         *     }
         */
        RuleCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            chain: components["schemas"]["Chain"];
            action: components["schemas"]["Action"];
            /** @default all */
            protocol: components["schemas"]["Protocol"];
            /** Src Ip */
            src_ip?: string | null;
            /** Dst Ip */
            dst_ip?: string | null;
            /** Src Port */
            src_port?: string | null;
            /** Dst Port */
            dst_port?: string | null;
            /** In Interface */
            in_interface?: string | null;
            /** Out Interface */
            out_interface?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Log Enabled
             * @default false
             */
            log_enabled: boolean;
            /** Log Prefix */
            log_prefix?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * RuleListItem
         * @description Una fila de la tabla del dashboard.
         *
         *     Deliberadamente mas corta que `RuleRead`: `description` es donde se explica
         *     el porque de la regla y puede ser largo, y multiplicado por las filas de una
         *     pagina es la mayor parte de la respuesta sin que se vea en pantalla.
         */
        RuleListItem: {
            /** Uuid */
            uuid: string;
            /** Name */
            name: string;
            chain: components["schemas"]["Chain"];
            action: components["schemas"]["Action"];
            protocol: components["schemas"]["Protocol"];
            /** Src Ip */
            src_ip?: string | null;
            /** Dst Ip */
            dst_ip?: string | null;
            /** Src Port */
            src_port?: string | null;
            /** Dst Port */
            dst_port?: string | null;
            /** Position */
            position: number;
            /** Enabled */
            enabled: boolean;
            sync_state: components["schemas"]["SyncState"];
            /** Hit Count */
            hit_count: number;
            /** Bytes Count */
            bytes_count: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RuleRead
         * @description Una regla completa, tal y como la ve la API.
         *
         *     Incluye lo que el usuario no escribe pero necesita ver: en que estado de
         *     sincronizacion esta, cuando se aplico por ultima vez y por que fallo.
         */
        RuleRead: {
            /** Uuid */
            uuid: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            chain: components["schemas"]["Chain"];
            table_name: components["schemas"]["Table"];
            /** Ip Version */
            ip_version: number;
            action: components["schemas"]["Action"];
            protocol: components["schemas"]["Protocol"];
            /** Src Ip */
            src_ip?: string | null;
            /** Dst Ip */
            dst_ip?: string | null;
            /** Src Port */
            src_port?: string | null;
            /** Dst Port */
            dst_port?: string | null;
            /** In Interface */
            in_interface?: string | null;
            /** Out Interface */
            out_interface?: string | null;
            /** Position */
            position: number;
            /** Enabled */
            enabled: boolean;
            /** Log Enabled */
            log_enabled: boolean;
            /** Log Prefix */
            log_prefix?: string | null;
            /** Expires At */
            expires_at?: string | null;
            sync_state: components["schemas"]["SyncState"];
            /** Last Error */
            last_error?: string | null;
            /** Applied At */
            applied_at?: string | null;
            /** Hit Count */
            hit_count: number;
            /** Bytes Count */
            bytes_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Created By */
            created_by?: string | null;
        };
        /**
         * RuleUpdate
         * @description Modificacion parcial: solo se toca lo que venga en el cuerpo.
         *
         *     Todos los campos son opcionales y valen `None` por defecto, asi que "no lo
         *     mandes" y "ponlo a null" se escriben igual en JSON. El servicio los distingue
         *     con `model_dump(exclude_unset=True)`, que es la razon de que este schema no
         *     herede de `_CamposDeRegla`: alli `name`, `chain` y `action` son obligatorios,
         *     y aqui no puede serlo ninguno.
         */
        RuleUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            chain?: components["schemas"]["Chain"] | null;
            action?: components["schemas"]["Action"] | null;
            protocol?: components["schemas"]["Protocol"] | null;
            /** Src Ip */
            src_ip?: string | null;
            /** Dst Ip */
            dst_ip?: string | null;
            /** Src Port */
            src_port?: string | null;
            /** Dst Port */
            dst_port?: string | null;
            /** In Interface */
            in_interface?: string | null;
            /** Out Interface */
            out_interface?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            /** Log Enabled */
            log_enabled?: boolean | null;
            /** Log Prefix */
            log_prefix?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * SyncState
         * @description Estado de sincronizacion entre la DB y iptables.
         *
         *     Esta distincion es el corazon del diseño: una regla puede existir en la DB y
         *     no estar aplicada al sistema.
         * @enum {string}
         */
        SyncState: "pending" | "applied" | "failed" | "drift";
        /**
         * Table
         * @description Tablas de iptables. El MVP solo usa `filter`.
         * @enum {string}
         */
        Table: "filter";
        /**
         * TokenPair
         * @description Respuesta de `/login` y `/refresh`.
         *
         *     `token_type` es literalmente `"bearer"` porque lo pide el RFC 6750 y porque
         *     los clientes OAuth2 genericos lo esperan. `expires_in` va en segundos, como
         *     manda el mismo RFC, para que el frontend pueda programar el refresco sin
         *     tener que decodificar el token.
         */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Validez del access token, en segundos.
             */
            expires_in: number;
        };
        /**
         * UserRead
         * @description El usuario tal y como lo ve la API. Sin `hashed_password`, obviamente.
         */
        UserRead: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email?: string | null;
            role: components["schemas"]["Role"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Login At */
            last_login_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_v1_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Alguna dependencia no responde. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Credenciales o token invalidos. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Credenciales o token invalidos. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Credenciales o token invalidos. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listar_api_v1_rules_get: {
        parameters: {
            query?: {
                /** @description Filtra por cadena. */
                chain?: components["schemas"]["Chain"] | null;
                /** @description Solo activas o solo inactivas. */
                enabled?: boolean | null;
                /** @description Busca en nombre y descripcion. */
                q?: string | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RuleListItem_"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_api_v1_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reordenar_api_v1_rules_reorder_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleListItem"][];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe una regla con ese uuid. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ver_api_v1_rules__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe una regla con ese uuid. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    borrar_api_v1_rules__uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe una regla con ese uuid. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modificar_api_v1_rules__uuid__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe una regla con ese uuid. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternar_api_v1_rules__uuid__toggle_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No existe una regla con ese uuid. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aplicar_api_v1_firewall_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El firewall no ha podido cumplir la orden. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    previsualizar_api_v1_firewall_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplyResponse"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El firewall no ha podido cumplir la orden. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    estado_api_v1_firewall_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FirewallStatus"];
                };
            };
            /** @description Falta el token o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El rol no alcanza. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description El firewall no ha podido cumplir la orden. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
